# Generated by Django 6.0.3 on 2026-08-09 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_created_by_user_custom_permissions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('CHEF_FACTURATION', 'Chef Facturation'), ('AGENT_FACTURATION', 'Agent Facturation'), ('COMMERCIAL', 'Commercial'), ('PAYEUR', 'Payeur'), ('EMPLOYE', 'Employé')], default='EMPLOYE', max_length=20),
        ),
    ]
