# Generated by Django 6.0.3 on 2026-07-16 11:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compte', models.CharField(max_length=20, unique=True, verbose_name='Compte')),
                ('raison_sociale', models.CharField(max_length=200, verbose_name='Raison Sociale')),
                ('code_commercial', models.CharField(blank=True, max_length=10, null=True, verbose_name='Code Commercial')),
                ('nom_commercial', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nom Commercial')),
                ('categorie', models.CharField(choices=[('GE', 'Grande Entreprise'), ('PE', 'Petite Entreprise'), ('P', 'Particulier'), ('OI', 'Organisme International'), ('EP', 'Entreprise Publique'), ('A', 'Association'), ('NR', 'Non Revenu')], default='PE', max_length=5, verbose_name='Catégorie Client')),
                ('adresse', models.TextField(blank=True, null=True, verbose_name='Adresse')),
                ('adresse2', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('statut', models.CharField(default='ACTIF', max_length=20, verbose_name='Statut')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date Création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date Modification')),
                ('payeur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companies', to=settings.AUTH_USER_MODEL, verbose_name='Payeur')),
            ],
            options={
                'verbose_name': 'Entreprise',
                'verbose_name_plural': 'Entreprises',
                'db_table': 'companies',
                'ordering': ['raison_sociale'],
            },
        ),
        migrations.CreateModel(
            name='Line',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msisdn', models.CharField(max_length=15, unique=True, verbose_name='Numéro Mobile')),
                ('utilisateur', models.CharField(blank=True, max_length=100, null=True, verbose_name='Utilisateur')),
                ('forfait', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Forfait (FCFA)')),
                ('cycle', models.CharField(choices=[('HYB1', 'Hybride 1'), ('HYB2', 'Hybride 2'), ('MON1', 'Mensuel 1')], default='MON1', max_length=10, verbose_name='Cycle de Facturation')),
                ('option_blackberry', models.CharField(blank=True, max_length=20, null=True, verbose_name='Option BlackBerry')),
                ('option_nolimit', models.CharField(blank=True, max_length=20, null=True, verbose_name='Option No Limit')),
                ('est_incognito', models.BooleanField(default=False, verbose_name='Incognito')),
                ('facture_detaillee', models.BooleanField(default=False, verbose_name='Facture Détaillée')),
                ('est_non_revenu', models.BooleanField(default=False, verbose_name='Non Revenu')),
                ('statut', models.CharField(default='ACTIF', max_length=20, verbose_name='Statut')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date Création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date Modification')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='billing.company', verbose_name='Entreprise')),
                ('employe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lines', to=settings.AUTH_USER_MODEL, verbose_name='Employé')),
            ],
            options={
                'verbose_name': 'Ligne',
                'verbose_name_plural': 'Lignes',
                'db_table': 'lines',
                'ordering': ['msisdn'],
            },
        ),
    ]
