# Generated by Django 6.0.3 on 2026-07-22 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='line',
            name='cycle',
            field=models.CharField(choices=[('HYB', 'Hybride'), ('OP', 'Opérationnel')], default='HYB', max_length=10, verbose_name='Cycle de Facturation'),
        ),
    ]
