# Generated by Django 6.0.3 on 2026-07-22 14:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_alter_line_cycle'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom du forfait')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Code')),
                ('type_forfait', models.CharField(choices=[('DATA', 'Data'), ('VOIX', 'Voix'), ('SMS', 'SMS'), ('MIXTE', 'Mixte')], default='MIXTE', max_length=20, verbose_name='Type de forfait')),
                ('prix_mensuel', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix mensuel (FCFA)')),
                ('quota_data_mo', models.IntegerField(blank=True, null=True, verbose_name='Quota Data (Mo)')),
                ('quota_minutes', models.IntegerField(blank=True, null=True, verbose_name='Quota Minutes')),
                ('quota_sms', models.IntegerField(blank=True, null=True, verbose_name='Quota SMS')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('est_actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date Création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date Modification')),
            ],
            options={
                'verbose_name': 'Forfait',
                'verbose_name_plural': 'Forfaits',
                'db_table': 'packages',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom du service')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Code')),
                ('type_service', models.CharField(choices=[('PASS', 'Pass'), ('OPTION', 'Option'), ('PROMO', 'Promotion')], default='OPTION', max_length=20, verbose_name='Type de service')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('est_actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date Création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date Modification')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'db_table': 'services',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_facture', models.CharField(max_length=50, unique=True, verbose_name='Numéro de facture')),
                ('periode_debut', models.DateField(verbose_name='Début de période')),
                ('periode_fin', models.DateField(verbose_name='Fin de période')),
                ('montant_ht', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Montant HT (FCFA)')),
                ('montant_tva', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Montant TVA (FCFA)')),
                ('montant_ttc', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Montant TTC (FCFA)')),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('EN_COURS', 'En cours'), ('VALIDEE', 'Validée'), ('PUBLIEE', 'Publiée'), ('PAYEE', 'Payée'), ('ANNULEE', 'Annulée')], default='BROUILLON', max_length=20, verbose_name='Statut')),
                ('date_emission', models.DateTimeField(auto_now_add=True, verbose_name="Date d'émission")),
                ('date_echeance', models.DateField(verbose_name="Date d'échéance")),
                ('fichier_pdf', models.FileField(blank=True, null=True, upload_to='factures/', verbose_name='Fichier PDF')),
                ('commentaire', models.TextField(blank=True, verbose_name='Commentaire')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date Création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date Modification')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='billing.company', verbose_name='Entreprise')),
            ],
            options={
                'verbose_name': 'Facture',
                'verbose_name_plural': 'Factures',
                'db_table': 'invoices',
                'ordering': ['-date_emission'],
            },
        ),
        migrations.CreateModel(
            name='HistoriqueFacturation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_action', models.CharField(choices=[('CREATION', 'Création'), ('MODIFICATION', 'Modification'), ('VALIDATION', 'Validation'), ('PUBLICATION', 'Publication'), ('PAIEMENT', 'Paiement'), ('ANNULATION', 'Annulation')], max_length=50, verbose_name="Type d'action")),
                ('ancien_statut', models.CharField(blank=True, max_length=20, verbose_name='Ancien statut')),
                ('nouveau_statut', models.CharField(max_length=20, verbose_name='Nouveau statut')),
                ('commentaire', models.TextField(blank=True, verbose_name='Commentaire')),
                ('date_action', models.DateTimeField(auto_now_add=True, verbose_name="Date de l'action")),
                ('utilisateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions_facturation', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique', to='billing.invoice', verbose_name='Facture')),
            ],
            options={
                'verbose_name': 'Historique Facturation',
                'verbose_name_plural': 'Historiques Facturation',
                'db_table': 'historique_facturation',
                'ordering': ['-date_action'],
            },
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('cycle_facturation', models.CharField(max_length=20, verbose_name='Cycle de facturation')),
                ('periode_debut', models.DateField(verbose_name='Début de période')),
                ('periode_fin', models.DateField(verbose_name='Fin de période')),
                ('date_publication', models.DateTimeField(auto_now_add=True, verbose_name='Date de publication')),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('EN_COURS', 'En cours'), ('VALIDEE', 'Validée'), ('PUBLIEE', 'Publiée'), ('PAYEE', 'Payée'), ('ANNULEE', 'Annulée')], default='PUBLIEE', max_length=20, verbose_name='Statut')),
                ('nombre_lignes_traitees', models.IntegerField(default=0, verbose_name='Nombre de lignes traitées')),
                ('montant_total', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Montant total (FCFA)')),
                ('fichier_pdf', models.FileField(blank=True, null=True, upload_to='publications/', verbose_name='Fichier PDF')),
                ('commentaire', models.TextField(blank=True, verbose_name='Commentaire')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date Création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date Modification')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publications', to=settings.AUTH_USER_MODEL, verbose_name='Agent')),
            ],
            options={
                'verbose_name': 'Publication',
                'verbose_name_plural': 'Publications',
                'db_table': 'publications',
                'ordering': ['-date_publication'],
            },
        ),
        migrations.CreateModel(
            name='Simulation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_simulation', models.DateTimeField(auto_now_add=True, verbose_name='Date de simulation')),
                ('montant_estime', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Montant estimé (FCFA)')),
                ('services_selectionnes', models.JSONField(default=list, verbose_name='Services sélectionnés')),
                ('resultat_detaille', models.JSONField(default=dict, verbose_name='Résultat détaillé')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simulations', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Simulation',
                'verbose_name_plural': 'Simulations',
                'db_table': 'simulations',
                'ordering': ['-date_simulation'],
            },
        ),
        migrations.CreateModel(
            name='TarifService',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_option', models.CharField(max_length=100, verbose_name="Nom de l'option")),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix (FCFA)')),
                ('duree_validite_heures', models.IntegerField(blank=True, null=True, verbose_name='Durée de validité (heures)')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('est_actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date Création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date Modification')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarifs', to='billing.service', verbose_name='Service')),
            ],
            options={
                'verbose_name': 'Tarif Service',
                'verbose_name_plural': 'Tarifs Services',
                'db_table': 'tarifs_services',
                'ordering': ['service', 'nom_option'],
            },
        ),
        migrations.CreateModel(
            name='Cycle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateTimeField(verbose_name='Date de début')),
                ('date_fin', models.DateTimeField(blank=True, null=True, verbose_name='Date de fin')),
                ('est_actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date Création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date Modification')),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cycles_services', to='billing.line', verbose_name='Ligne')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cycles_lignes', to='billing.service', verbose_name='Service')),
            ],
            options={
                'verbose_name': 'Cycle Service',
                'verbose_name_plural': 'Cycles Services',
                'db_table': 'cycles',
                'ordering': ['-date_debut'],
                'unique_together': {('line', 'service', 'date_debut')},
            },
        ),
    ]
