# Generated by Django 6.0.3 on 2026-08-02 10:17

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_invoice_line'),
    ]

    operations = [
        migrations.AlterField(
            model_name='line',
            name='forfait',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Forfait (FCFA)'),
        ),
        migrations.AlterField(
            model_name='package',
            name='prix_mensuel',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Prix mensuel (FCFA)'),
        ),
        migrations.AlterField(
            model_name='tarifservice',
            name='prix',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Prix (FCFA)'),
        ),
    ]
