# Generated by Django 6.0.3 on 2026-08-05 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_alter_line_forfait_alter_package_prix_mensuel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='date_effet',
            field=models.DateField(blank=True, null=True, verbose_name='Date effet'),
        ),
        migrations.AddField(
            model_name='company',
            name='est_exonere',
            field=models.BooleanField(default=False, verbose_name='Exonéré'),
        ),
        migrations.AddField(
            model_name='company',
            name='est_incognito_defaut',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='company',
            name='est_non_revenu_defaut',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='company',
            name='facture_detaillee_defaut',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='company',
            name='international_defaut',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='company',
            name='internet_defaut',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='company',
            name='option_blackberry_defaut',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='company',
            name='option_nolimit_defaut',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='company',
            name='roaming_defaut',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='line',
            name='est_international',
            field=models.BooleanField(default=False, verbose_name='International'),
        ),
        migrations.AddField(
            model_name='line',
            name='est_internet',
            field=models.BooleanField(default=False, verbose_name='Internet'),
        ),
        migrations.AddField(
            model_name='line',
            name='est_roaming',
            field=models.BooleanField(default=False, verbose_name='Roaming'),
        ),
    ]
