# Generated by Django 6.0.3 on 2026-08-05 14:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_company_date_effet_company_est_exonere_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Commercial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('prenom', models.CharField(max_length=100, verbose_name='Prénom')),
                ('matricule', models.CharField(max_length=30, unique=True, verbose_name='Matricule / Code commercial')),
                ('telephone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('est_actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date Création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date Modification')),
            ],
            options={
                'verbose_name': 'Commercial',
                'verbose_name_plural': 'Commerciaux',
                'db_table': 'commerciaux',
                'ordering': ['nom', 'prenom'],
            },
        ),
        migrations.AddField(
            model_name='company',
            name='adresse_ligne2',
            field=models.TextField(blank=True, verbose_name='Adresse ligne 2'),
        ),
        migrations.AddField(
            model_name='company',
            name='date_fin',
            field=models.DateField(blank=True, null=True, verbose_name='Date de fin'),
        ),
        migrations.AddField(
            model_name='company',
            name='date_resiliation',
            field=models.DateField(blank=True, null=True, verbose_name='Date de résiliation'),
        ),
        migrations.AddField(
            model_name='company',
            name='email_facturation',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email de facturation'),
        ),
        migrations.AddField(
            model_name='company',
            name='est_resilie',
            field=models.BooleanField(default=False, verbose_name='Résilié'),
        ),
        migrations.AddField(
            model_name='company',
            name='mode_reglement',
            field=models.CharField(choices=[('CHEQUE', 'Chèque'), ('VIREMENT', 'Virement'), ('ESPECES', 'Espèces')], default='VIREMENT', max_length=20, verbose_name='Mode de règlement'),
        ),
        migrations.AddField(
            model_name='company',
            name='motif_exoneration',
            field=models.TextField(blank=True, verbose_name="Motif d'exonération"),
        ),
        migrations.AddField(
            model_name='company',
            name='motif_resiliation',
            field=models.TextField(blank=True, verbose_name='Motif de résiliation'),
        ),
        migrations.AddField(
            model_name='company',
            name='observation',
            field=models.TextField(blank=True, verbose_name='Observation'),
        ),
        migrations.AddField(
            model_name='company',
            name='observation_resiliation',
            field=models.TextField(blank=True, verbose_name='Observation résiliation'),
        ),
        migrations.AddField(
            model_name='company',
            name='statut_factures',
            field=models.CharField(choices=[('ACTIF', 'Actif'), ('SUSPENDU', 'Suspendu'), ('CLOS', 'Clos'), ('EN_ATTENTE', 'En attente')], default='EN_ATTENTE', max_length=20, verbose_name='Statut de facturation'),
        ),
        migrations.AddField(
            model_name='company',
            name='type_revenu',
            field=models.CharField(blank=True, max_length=50, verbose_name='Type de revenu'),
        ),
        migrations.CreateModel(
            name='AuditContrat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_action', models.CharField(choices=[('CREATION', 'Création du contrat'), ('MODIFICATION', 'Modification'), ('CHANGEMENT_STATUT', 'Changement de statut de facturation'), ('CHANGEMENT_COMMERCIAL', 'Changement de commercial'), ('CHANGEMENT_SERVICES', 'Changement des services par défaut'), ('RESILIATION', 'Résiliation'), ('MODIFICATION_RESILIATION', 'Modification résiliation'), ('AJOUT_LIGNE', 'Ajout de ligne'), ('MODIFICATION_LIGNE', 'Modification services ligne')], max_length=50, verbose_name="Type d'action")),
                ('description', models.TextField(verbose_name='Description')),
                ('anciennes_valeurs', models.JSONField(blank=True, default=dict, verbose_name='Anciennes valeurs')),
                ('nouvelles_valeurs', models.JSONField(blank=True, default=dict, verbose_name='Nouvelles valeurs')),
                ('date_action', models.DateTimeField(auto_now_add=True, verbose_name="Date de l'action")),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_log', to='billing.company', verbose_name='Contrat')),
                ('utilisateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audits_contrats', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Audit Contrat',
                'verbose_name_plural': 'Audits Contrats',
                'db_table': 'audit_contrats',
                'ordering': ['-date_action'],
            },
        ),
        migrations.AddField(
            model_name='company',
            name='commercial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contrats', to='billing.commercial', verbose_name='Commercial'),
        ),
    ]
