# Generated by Django 6.0.3 on 2026-08-06 10:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0007_commercial_audit_company_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='date_emission_pdf',
            field=models.DateField(blank=True, null=True, verbose_name='Date édition PDF'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='numero_facture_pdf',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Numéro facture PDF'),
        ),
        migrations.CreateModel(
            name='NotificationFacture',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('canal', models.CharField(choices=[('EMAIL', 'E-mail'), ('SMS', 'SMS')], max_length=10)),
                ('destinataire', models.CharField(max_length=254)),
                ('statut', models.CharField(choices=[('ENVOYEE', 'Envoyée'), ('ECHEC', 'Échec'), ('NON_CONFIGUREE', 'Service non configuré')], max_length=20)),
                ('detail', models.TextField(blank=True)),
                ('date_envoi', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='billing.invoice')),
            ],
            options={
                'db_table': 'notifications_factures',
                'ordering': ['-date_envoi'],
            },
        ),
    ]
