# Generated by Django 6.0.3 on 2026-08-09 10:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0008_invoice_date_emission_pdf_invoice_numero_facture_pdf_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='commercial',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profil_commercial', to=settings.AUTH_USER_MODEL, verbose_name='Compte utilisateur commercial'),
        ),
    ]
