# Generated by Django 6.0.3 on 2026-08-09 17:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0009_commercial_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('compte_propose', models.CharField(max_length=20)),
                ('raison_sociale', models.CharField(max_length=200)),
                ('payload', models.JSONField(default=dict)),
                ('password_payeur_hash', models.CharField(max_length=128)),
                ('statut', models.CharField(choices=[('PENDING', 'En attente de validation'), ('APPROVED', 'Approuvée'), ('REJECTED', 'Rejetée')], default='PENDING', max_length=12)),
                ('decision_comment', models.TextField(blank=True)),
                ('date_soumission', models.DateTimeField(auto_now_add=True)),
                ('date_decision', models.DateTimeField(blank=True, null=True)),
                ('commercial', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='demandes_contrat', to='billing.commercial')),
                ('company', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demande_origine', to='billing.company')),
                ('decision_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes_contrat_decidees', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='demandes_contrat_soumises', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'contract_requests',
                'ordering': ['-date_soumission'],
            },
        ),
    ]
