# Generated by Django 6.0.3 on 2026-08-10 14:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0010_contractrequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TraitementPDF',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fichier_source', models.FileField(upload_to='imports_pdf/%Y/%m/')),
                ('type_facture', models.CharField(default='SOM', max_length=3)),
                ('cycle', models.CharField(blank=True, max_length=20)),
                ('periode_debut', models.DateField(blank=True, null=True)),
                ('periode_fin', models.DateField(blank=True, null=True)),
                ('auto_match', models.BooleanField(default=True)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('EN_COURS', 'En cours'), ('TERMINE', 'Terminé'), ('ECHEC', 'Échec')], default='EN_ATTENTE', max_length=20)),
                ('task_id', models.CharField(blank=True, max_length=100)),
                ('progression', models.PositiveSmallIntegerField(default=0)),
                ('resultat', models.JSONField(blank=True, default=dict)),
                ('erreur', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_debut', models.DateTimeField(blank=True, null=True)),
                ('date_fin', models.DateTimeField(blank=True, null=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traitements_pdf', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'traitements_pdf',
                'ordering': ['-date_creation'],
            },
        ),
    ]
