# Generated by Django 6.0.3 on 2026-08-21 18:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0011_traitementpdf'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationfacture',
            name='statut',
            field=models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('ENVOYEE', 'Envoyée'), ('ECHEC', 'Échec'), ('NON_CONFIGUREE', 'Service non configuré')], max_length=20),
        ),
        migrations.CreateModel(
            name='BlocFacturesTest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fichier_pdf', models.FileField(upload_to='blocs_test/%Y/%m/', verbose_name='Bloc PDF')),
                ('nom_fichier', models.CharField(max_length=255)),
                ('type_facture', models.CharField(choices=[('SOM', 'Sommaire'), ('GLO', 'Globale')], max_length=3)),
                ('periode_debut', models.DateField()),
                ('periode_fin', models.DateField()),
                ('date_emission', models.DateField()),
                ('nombre_factures', models.PositiveSmallIntegerField()),
                ('montant_total_ttc', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('libelle', models.CharField(blank=True, max_length=120)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('createur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocs_factures_test', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
            ],
            options={
                'verbose_name': 'Bloc de factures de test',
                'verbose_name_plural': 'Blocs de factures de test',
                'db_table': 'blocs_factures_test',
                'ordering': ['-date_creation'],
            },
        ),
    ]
